# Generated by Django 6.0.5 on 2026-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='university',
            new_name='major',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='한국어', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('local', '내국인'), ('international', '외국인')], default='international', max_length=20),
        ),
    ]
